config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :pools
  resources :picks
  resources :pool_participants
  resources :tournaments
  get 'errors/not_admin' => 'error#not_admin'
  root "pools#index"
  get "pools/:id/join_pool", to: "pools#show_join_pool", as: "show_join_pool"
  post "pools/:id/join_pool", to: "pools#join_pool", as: "join_pool"
  post "pools/:id/add_additional_entrant_to_pool", to: "pools#add_additional_entrant_to_pool", as: "add_additional_entrant_to_pool"

end

app/models/pool.rb
class Pool < ActiveRecord::Base
	belongs_to :creator, class_name: :User
	belongs_to :tournament
	has_many :tournament_golfers, through: :tournament
	has_many :golfers, through: :tournament_golfers
	has_many :pool_participants, dependent: :destroy

	# validates_inclusion_of :pool_type, :in => ["NFL", "PGA", "NBA", "NHL", "MLB"]
	validates :name, :tournament_id, presence: true

	def sort_pool_participants_by_score
		@disqualified_participants = []
		@scored_participants = []
		if pool_participants.count > 1
			pool_participants.each do |participant|
			participant.total_score.is_a?(Integer) ? @scored_participants.push(participant) : @disqualified_participants.push(participant)
			end
			if @scored_participants.count > 1
				@scored_participants = @scored_participants.sort_by {|a| a.total_score}
			end
			if @disqualified_participants.count > 0
				@scored_participants += @disqualified_participants
			end
		else
			@scored_participants = pool_participants
		end
		@scored_participants
	end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController

	before_action :must_be_logged_in, only: [:new, :create, :edit, :destroy, :show_join_pool, :join_pool, :add_additional_entrant_to_pool]


	def show_join_pool
		@join_pool = Pool.new
	end

	def join_pool
		@pool = Pool.find(params[:id])
		# if user clicks on join pool and is not signed in then 
		# User clicks join pool button
		# If not signed in when clicking button, then they are redirected to login
		# If signed in, redirect them to join_pool
		# display form with password on join_pool - add custom validation for password checking
		# if the user has a valid email and password, then they are added to pool_participants and the pool.number_picks Picks are created for them, with the golfer blank, and they are redirectd to the pools pick page
		if params[:password] == @pool.password && !currently_participates_in_pool?(@pool.id)
			@pool_participant = PoolParticipant.create(user_id: current_user.id, pool_id: @pool.id)
			@pool.number_picks.times do
				Pick.create(pool_id: @pool.id, user_id: current_user.id, pool_participant_id: @pool_participant.id)
			end
			redirect_to pool_path(@pool)
		else
			flash[:errors] = "Either password incorrect or you are already a member of this pool"
			redirect_to show_join_pool_path(@pool)
		end
	end
  
	def index
		@users_pools = users_pools
		@owned_pools = owned_pools
		@all_pools = Pool.all
	end

	def new
		@pool = Pool.new
		@available_tournaments = Tournament.where(status: "upcoming")
	end

	def create
		@pool = Pool.new(pool_params)
		if @pool.save
			redirect_to @pool
		else
			@pool_errors = @pool.errors.full_messages
			flash[:errors] = @pool_errors
      		redirect_to new_pool_path
      	end
	end

	def show
		@pool = Pool.find(params[:id])
		@pool_participants = PoolParticipant.where(pool_id: @pool.id)
		@picks = user_signed_in? ? Pick.where(user_id: current_user.id, pool_id: @pool.id) : nil
		if @picks
			@picks1 = @picks.slice(0..@pool.number_picks-1)
			@picks2 = @picks.slice(@pool.number_picks..(@pool.number_picks * 2)-1)
			@picks3 = @picks.slice((@pool.number_picks * 2)..(@pool.number_picks * 3)-1)
			@picks4 = @picks.slice((@pool.number_picks * 3)..(@pool.number_picks * 4)-1)
			@picks5 = @picks.slice((@pool.number_picks * 4)..(@pool.number_picks * 5)-1)
		end

	end

	def edit
		@pool = Pool.find(params[:id])
		must_be_owner(@pool.creator_id)
	end


	def update
		@pool = Pool.find(params[:id])
		must_be_owner(@pool.creator_id)
		if @pool.update_attributes(pool_params)
			redirect_to @pool
		else
			flash[:errors] = @pool.errors.full_messages
			redirect_to edit_pool_path
		end
	end

	def destroy
		Pool.destroy(params[:id])
		flash[:message] = "Pool " + params[:id] + " successfully deleted"
		redirect_to root_path
	end

	def add_additional_entrant_to_pool
		@pool = Pool.find(params[:id])
		@pool_participant = PoolParticipant.create(pool_id: @pool.id, user_id: current_user.id)
		@pool.number_picks.times do
			Pick.create(pool_id: @pool.id, user_id: current_user.id, pool_participant_id: @pool_participant.id)
		end
		redirect_to pool_path(@pool)
	end



	private

	def pool_params
		params.require(:pool).permit(:name, :creator, :pool_type, :tournament_id, :number_picks, :number_golfers_for_scoring, :password).merge(creator_id: current_user.id)
	end

end

app/views/pools/_form.html.erb
<% if flash[:errors] %>
  <div class="flash-errors"><%= flash[:errors] %></div>
<% end %>

<%= form_for @pool do |f| %>

<div class="pool-form-group">
  <div class="pool-form-pair">
    <%= f.label :name %> *
    <%= f.text_field :name %>
  </div>
</div> 

<div class="pool-form-group">
  <div class="pool-form-pair">
    <%= f.label :password, "Password for pool" %> *
    <%= f.password_field :password %>
  </div>
</div> 

<div class="pool-form-group">
  <div class="pool-form-pair">
    <%= f.label :number_picks %> *
    <%= f.text_field :number_picks %>
  </div>
</div> 

<div class="pool-form-group">
  <div class="pool-form-pair">
    <%= f.label :number_golfers_for_scoring %> *
    <%= f.text_field :number_golfers_for_scoring %>
  </div>
</div> 

<div class="pool-form-group">
  <div class="pool-form-pair">
    <%= f.label :tournament_id%> *
    <%= select("pool", "tournament_id", Tournament.where(status: "upcoming").collect {|t| [ t.name, t.id ] }, {include_blank: true}, :class => "browser-default") %>
  </div>
</div>

<div class="pool-form-group">
  <div class="pool-form-pair">
    <%= f.label :pool_type %> *
    <%= select("pool", "pool_type", ["PGA", "NFL", "NBA", "NHL", "MLB"], {include_blank: true}, :class => "browser-default") %>
  </div>
</div>


  <div class="pool-form-indented">
    <p><%= f.submit :class => "waves-effect waves-light btn"%></p>

    <p>* - Indicates required field</p>
  </div>
<% end %>

app/views/pools/edit.html.erb
<div class="form-container">
    <div class="pool-form">
      <h1>Edit Pool </h1>
        <%= render "pools/form"%>
        <%= link_to "Return to all pools without saving", pools_path %>
    </div>
</div>

app/views/pools/index.html.erb
<% if flash[:message] %>
  <div class="flash-message"><%= flash[:message] %></div>
<% end %>


<% if user_signed_in? %> 
  <h3> New Pool </h3>
    <%= link_to('Create a new pool', new_pool_path, :class => "waves-effect waves-light btn") %> 
<% end %>

<br>
<br>

<% if @users_pools %>
  <h3> Pools you belong to </h3>
  <% @users_pools.each do |pool| %>
    <p> <%= link_to(pool.name, pool_path(pool)) %> </p>
  <% end %> 
  <br>
<% end %>

<% if @owned_pools %>
  
  <h3>Pools you own </h3>
  <% @owned_pools.each do |pool| %>
    <p>
      <%= link_to(pool.name, pool_path(pool)) %>
      <%= link_to("Edit", edit_pool_path(pool), :class => "waves-effect waves-light btn") %>
    </p>
  <% end %> 
  <br>
<% end %>

<h3> All Pools </h3>

<% @all_pools.each do |pool| %>
  <p> 
    <%= link_to(pool.name, pool_path(pool)) %>  
    <% if !currently_participates_in_pool?(pool.id) %>
      <%= link_to("Join", show_join_pool_path(pool), :class => "waves-effect waves-light btn") %> 
    <% end %>   
  </p>
<% end %> 

<% if user_signed_in? and current_user.admin? %>
  <br>
  <h3>Administrator Tournament Manager </h3>
  <%= link_to "Tournament Manager", tournaments_path %>
<% end %>

app/views/pools/new.html.erb
<div class="form-container">
    <div class="pool-form">
      <h1>New Pool </h1>
        <%= render "pools/form"%>
        <%= link_to "Return to all pools without saving", pools_path %>
    </div>
</div>

app/views/pools/show.html.erb
<h3> <%= @pool.name %> </h3>

<p> Please remember to read the tournament rules before making your picks. Reference <a href="http://www.owgr.com/ranking" target="_blank"> http://www.owgr.com/ranking </a> for golfers rankings. </p>


<% if currently_participates_in_pool?(@pool.id) %>
	<% if !@picks.empty?  %>
			<%= render partial: "picks/show", collection: @picks1.sort_by(&:id), as: :pick, locals: {pool: @pool} %>
	<% end %>
	<% if @picks2 && !@picks2.empty? %>
	<br>
		Entrant 2:
			<%= render partial: "picks/show", collection: @picks2.sort_by(&:id), as: :pick, locals: {pool: @pool} %>
	<% end %>
	<% if @picks3 && !@picks3.empty? %>
	<br>
		Entrant 3:
			<%= render partial: "picks/show", collection: @picks3.sort_by(&:id), as: :pick, locals: {pool: @pool} %>
	<% end %>
	<% if @picks4 && !@picks4.empty? %>
		<br>
		Entrant 4:
			<%= render partial: "picks/show", collection: @picks4.sort_by(&:id), as: :pick, locals: {pool: @pool} %>
	<% end %>
	<% if @picks5 && !@picks5.empty? %>
		<br>
		Entrant 5:
			<%= render partial: "picks/show", collection: @picks5.sort_by(&:id), as: :pick, locals: {pool: @pool} %>
	<% else %>
		<%= link_to "Add additional entrant", add_additional_entrant_to_pool_path, method: "post", :class => "waves-effect waves-light btn" %>
	<% end %>

<% else %>
	<%= link_to("Join", show_join_pool_path, :class => "waves-effect waves-light btn") %>
<% end %>

<% if owner?(@pool.creator_id) %>
<br>
<div id = "pool-owner-actions">
	<h5 id="edit-pool-link"> <%= link_to("Edit Pool", edit_pool_path(@pool), :class => "waves-effect waves-light btn") %> </h5>
	<h5 id="delete-pool-button"> <%= button_to("Delete Pool", pool_path(@pool), data: { confirm: "Are you sure?" }, method: :delete, :class => "waves-effect waves-light red btn") %> </h5>
</div>
<% end %>

<br>

<table border=1 id="pool-picks-table">
	<!-- Header row -->
	<tr> 
		<th class='right-border bottom-border'> Entrant name </th>
		<% @pool.number_picks.times do |time| %>
			<th class='right-border bottom-border'> Pick <%= time + 1%> </th>
		<% end %>
		<th class='bottom-border'> Total score </th>
	</tr>
	
	<% @pool.sort_pool_participants_by_score.each do |participant| %>
		<!-- entrant name and picks -->
		<tr> 
			<td class='right-border top-border'> <%= participant.user.abbreviated_name %> </td>
			<!-- if tournament is ongoing, or if the entrant is the current user, show the picks -->
			<% if (@pool.tournament.status == "ongoing" || @pool.tournament.status == "completed") || (user_signed_in? && participant.user.id == current_user.id) %>
				<% participant.picks.each do |pick| %>
					<td class='right-border top-border'> <%if pick.golfer %> <%= pick.golfer.full_name %> <%end%></td>
				<% end %>
			<% else %>
				 <td class='right-border top-border'> Hidden </td>		
			<% end %>

		 </tr>
		<!-- Entrant subscores and total -->
		<% if participant.picks_made? && (@pool.tournament.status == "ongoing" || @pool.tournament.status == "completed") %>
			<tr> <td class='right-border'> </td>  <% participant.picks.each do |pick| %>
				<td class='right-border'> <%= pick.golfers_total %> </td>
			<%end%> 
			<td> <%= participant.total_score %> </td>
			</tr>
		<% end %>
	<% end %>

</table>

<br> <br>


<% if @pool.pool_type == "PGA" %>
	<%= render "pools/golf_pool_show" %>
<% elsif @pool.pool_type == "NFL" %>
	<%= render "pools/football_pool_show" %>
<% elsif @pool.pool_type == "NHL" %>
	<%= render "pools/hockey_pool_show" %>
<% elsif @pool.pool_type == "NBA" %>
	<%= render "pools/basketball_pool_show" %>
<% elsif @pool.pool_type == "MLB" %>
	<%= render "pools/baseball_pool_show" %>
<% end %>

app/views/pools/show_join_pool.html.erb
<% if flash[:errors] %>
  <div class="flash-errors"><%= flash[:errors] %></div>
<% end %>

<%= form_tag("/pools/#{params[:id]}/join_pool", method: :post) do %>

<div class="join-pool-form-group">
  <div class="join-pool-form-pair">
    <%= label_tag(:password, "Password for pool: ") %>
    <%= password_field_tag(:password) %>
  </div>
</div>

  <div class="join-pool-form-indented">
    <p><%= submit_tag("Join", :class => "waves-effect waves-light btn") %></p>

  </div>
<% end %>