config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :pools
  resources :picks
  resources :pool_participants
  resources :tournaments
  get 'errors/not_admin' => 'error#not_admin'
  root "pools#index"
  get "pools/:id/join_pool", to: "pools#show_join_pool", as: "show_join_pool"
  post "pools/:id/join_pool", to: "pools#join_pool", as: "join_pool"
  post "pools/:id/add_additional_entrant_to_pool", to: "pools#add_additional_entrant_to_pool", as: "add_additional_entrant_to_pool"

end

app/models/tournament.rb
require 'nokogiri'
require 'open-uri'
require 'watir'
# require 'phantomjs'
# if Rails.env.development?
# 	# Selenium::WebDriver::PhantomJS.path = "bin/phantomjs-mac"
# 	chromedriver_path = File.join(File.absolute_path('../..', File.dirname(__FILE__)),"bin","chromedriver-mac")
# 	puts chromedriver_path
# 	Selenium::WebDriver::Chrome.driver_path = chromedriver_path
# elsif Rails.env.production?
# 	# Selenium::WebDriver::PhantomJS.path = "bin/phantomjs-ubuntu"
# 	# chromedriver_path = File.join(File.absolute_path('../..', File.dirname(__FILE__)),"bin","chromedriver-linux")
# 	# Selenium::WebDriver::Chrome.driver_path = chromedriver_path
# end

if Rails.env.production?
	chrome_bin = ENV.fetch('GOOGLE_CHROME_SHIM', nil)
	Selenium::WebDriver::Chrome.path = chrome_bin
end

# chrome_bin = ENV.fetch('GOOGLE_CHROME_SHIM', nil)

# chrome_opts = chrome_bin ? { "chromeOptions" => { "binary" => chrome_bin } } : {}

class Tournament < ActiveRecord::Base
	has_many :pools, dependent: :destroy
	has_many :tournament_golfers, dependent: :destroy
	has_many :golfers, through: :tournament_golfers
	has_many :rounds, through: :tournament_golfers

	validates_inclusion_of :status, :in => ["upcoming", "completed", "ongoing", "preparing"]

	validates :name, :url, presence: true


	def initialize_pga_tournament_info
		browser = Watir::Browser.new :chrome, headless: true
		browser.goto url
		doc = Nokogiri::HTML.parse(browser.html)
		# options = Selenium::WebDriver::Chrome::Options.new
		# options.add_argument('--headless')
		# driver = Selenium::WebDriver.for :chrome, options: options
		# player_blocks = driver.find_elements(:css, ".player-block")
		# puts player_blocks
		doc.css(".player-block").each do |player_block|
			puts 'in player block'
			css_golfer_id = player_block.css("img.player-img").attribute("id").value
			golfer_id = css_golfer_id.gsub("player-", "")
			@golfer = Golfer.find_by(pga_player_id: golfer_id)
			@tournament_golfer = nil
			puts @golfer
			if !@golfer
				name_text = player_block.css(".player-name").text
				matches = name_text.match(/(\w+),\s*(\w+)/)
				first_name = matches[2]
				last_name = matches[1]
				profile_url = "http://www.pgatour.com/players/player.#{golfer_id}." + first_name.gsub(".", "-") + "-" + last_name.gsub(".", "-") + ".html"
				@golfer = Golfer.create(pga_player_id: golfer_id, first_name: first_name, last_name: last_name, pga_profile_url: profile_url)
				@tournament_golfer = TournamentGolfer.create(golfer_id: @golfer.id, tournament_id: self.id)
			elsif TournamentGolfer.where(golfer_id: @golfer.id, tournament_id: self.id).empty?
				@tournament_golfer = TournamentGolfer.create(golfer_id: @golfer.id, tournament_id: self.id)
			end
			next if !@tournament_golfer
			4.times do |x|
				Round.create(round_number: x+1, tournament_golfer_id: @tournament_golfer.id)
			end
		end
		self.update(instantiated?: true)
		browser.close
		return true
	end

	def update_current_pga_tournament_info
		browser = Watir::Browser.new :chrome, headless: true
		browser.goto "http://www.pgatour.com/leaderboard.html"
		doc = Nokogiri::HTML.parse(browser.html)
		# rows = doc.css(".leaderboard-main-content").xpath("div[starts-with(@class, 'player-row-')]")
		doc.css(".leaderboard-item").each do |row|
			pga_player_id = row.attribute("data-pid").value
			@golfer = Golfer.find_by(pga_player_id: pga_player_id)
			# necessary to wrap update logic in an if statment, only executes when golfer is found
			# this saves the case when the substitute player cannot be found
			# a more complete solution is to instantiate a new golfer and tournament golfer if this guy doesnt exist
			if @golfer
				@tournament_golfer = TournamentGolfer.find_by(golfer_id: @golfer.id, tournament_id: self.id)
				round_counter = 1
				next if !@tournament_golfer
				@tournament_golfer.update(total: row.css(".col-total").text.strip)
				if row.css("td:nth-child(2)").text.strip == "CUT"
					@tournament_golfer.update(total: "CUT")
				end
				row.css(".col-r").each do |round_data|
					@round = Round.find_by(round_number: round_counter, tournament_golfer_id: @tournament_golfer.id)
					if @round
						@round.update(total_strokes: round_data.text.strip.to_i) 
					end
					round_counter += 1
				end
			end
		end
		browser.close
		return true
	end

	def self.instantiate_tournaments
		@uninstantiated_tournaments = Tournament.where(instantiated?: false)
		@uninstantiated_tournaments.each do |tournament|
			tournament.initialize_pga_tournament_info
			tournament.update(instantiated?: true)
		end
	end

	def self.update_statuses
		current_time = Time.current.strftime("%Y-%m-%d %H:%M:%S")
		current_date = Time.current.strftime("%Y-%m-%d")
		Tournament.where.not(status: "completed").each do |tournament|
			tournaments_start_time = tournament.start_date_and_time.strftime("%Y-%m-%d %H:%M:%S")
			tournaments_start_date = tournament.start_date_and_time.strftime("%Y-%m-%d")
			tournaments_end_time = tournament.end_date_and_time.strftime("%Y-%m-%d %H:%M:%S")
			if tournament.status == "upcoming" || tournament.status == "preparing"
				if tournaments_start_time <= current_time
					tournament.update(status: "ongoing")
				elsif tournaments_start_date == current_date
					tournament.update(status: "preparing")
				end					
			elsif tournament.status == "ongoing"
				if tournaments_end_time <= current_date
					tournament.update(status: "completed")
				end
			end
		end
	end

	def self.update_ongoing
		Tournament.where(status: "ongoing").each do |tournament|
			tournament.update_current_pga_tournament_info
		end
	end


end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

	before_action :must_be_admin, except: [:show, :index]

	def index
		@tournaments = Tournament.all
	end

	def new
		@tournament = Tournament.new
	end

	def create
		@tournament = Tournament.new(tournament_params)
		if @tournament.save
			redirect_to @tournament
		else
			@tournament_errors = @tournament.errors.full_messages
			flash[:errors] = @tournament_errors
      		redirect_to new_tournament_path
      	end
	end

	def show
		@tournament = Tournament.find(params[:id])
	end

	def edit
		@tournament = Tournament.find(params[:id])
	end


	def update
		@tournament = Tournament.find(params[:id])
		if @tournament.update_attributes(tournament_params)
			redirect_to @tournament
		else
			flash[:errors] = @tournament.errors.full_messages
			redirect_to edit_tournament_path
		end
	end

	def destroy
	end

	def initialize_data_after_create
		@tournament.initialize_pga_tournament_info
	end


	private

	def tournament_params
		params.require(:tournament).permit(:name, :url, :strokes_per_round_to_par, :start_date_and_time, :end_date_and_time)
	end

end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<% if flash[:errors] %>
  <div class="flash-errors"><%= flash[:errors] %></div>
<% end %>

<%= form_for @tournament do |f| %>

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <%= f.label :name %> *
    <%= f.text_field :name %>
  </div>
</div> 

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <%= f.label :url %> *
    <%= f.text_field :url %>
  </div>
</div>

<div class="pool-form-group">
  <div class="pool-form-pair">
    <%= f.label :tournament_id%> *
    <%= select("tournament", "status", ["upcoming", "completed", "ongoing"], {include_blank: true}, :class => "browser-default") %>
  </div>
</div>

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <%= f.label :strokes_per_round_to_par %> *
    <%= f.text_field :strokes_per_round_to_par %>
  </div>
</div>

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <%= f.label :start_date_and_time %> *
    <%= f.text_field :start_date_and_time %>
    <br> <span style="color:grey; font-size:12px;" >(Please format as 'YYYY-MM-DD HH:MM:SS' - using military time for hours - and using UTC for time zone) </span>
  </div>
</div>

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <%= f.label :end_date_and_time, "End date and time " %> *
    <%= f.text_field :end_date_and_time %>
  </div>
</div>

  <div class="tournament-form-indented">
    <p><%= f.submit :class => "waves-effect waves-light btn" %></p>

    <p>* - Indicates required field</p>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<div class="form-container">
    <div class="tournament-form">
      <h1>Edit tournament </h1>
        <%= render "tournaments/form"%>
        <%= link_to "Return to all tournaments without saving", tournaments_path %>
    </div>
</div>

app/views/tournaments/index.html.erb
<h3> New Tournament </h3>
<%= link_to("Create a new tournament", new_tournament_path, :class => "waves-effect waves-light btn") %>

<br>
<br>

<h3> All Tournaments </h3>
<% if !@tournaments.empty? %>
	<% @tournaments.each do |tournament| %>
		<p> 
			<%= link_to(tournament.name, tournament_path(tournament))%> 
			<% if current_user && current_user.admin? %>
				<%= link_to("Edit", edit_tournament_path(tournament), :class => "waves-effect waves-light btn") %>
			<% end %> 
		</p>
	<% end %>

<% else %>
	
		<h1> Currently there are no tournaments set up. 
			<% if current_user && current_user.admin? %>
				You can set one up <%= link_to "here", new_tournament_path, :class => "waves-effect waves-light btn" %>
			<% end %>
		</h1>
<% end %>

app/views/tournaments/new.html.erb
<div class="form-container">
    <div class="tournament-form">
      <h1>New tournament </h1>
        <%= render "tournaments/form"%>
        <%= link_to "Return to all tournaments without saving", tournaments_path %>
    </div>
</div>

app/views/tournaments/show.html.erb
<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <b><%= label_tag :name %> </b>
    <%= @tournament.name %>
  </div>
</div> 

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <b><%= label_tag :url %> </b>
    <%=  @tournament.url %>
  </div>
</div>

<div class="pool-form-group">
  <div class="pool-form-pair">
    <b><%= label_tag :tournament_id%> </b>
    <%= select("tournament", "status", ["upcoming", "completed", "ongoing"]) %>
  </div>
</div>

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <b><%= label_tag :strokes_per_round_to_par %> </b>
    <%=  @tournament.strokes_per_round_to_par %>
  </div>
</div>

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <b><%= label_tag :start_date_and_time %> </b>
    <%=  @tournament.start_date_and_time %>
  </div>
</div>

<div class="tournament-form-group">
  <div class="tournament-form-pair">
    <b><%= label_tag :end_date_and_time, "End date and time " %> </b>
    <%=  @tournament.end_date_and_time %>
  </div>
</div>

<br>

<%= link_to("Edit Tournament", edit_tournament_path(@tournament), :class => "waves-effect waves-light btn") %>